/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ApiHatchesRouteImport } from './routes/api/hatches'
import { Route as ApiPatternsIndexRouteImport } from './routes/api/patterns/index'
import { Route as ApiPatternsIdRouteImport } from './routes/api/patterns/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHatchesRoute = ApiHatchesRouteImport.update({
  id: '/api/hatches',
  path: '/api/hatches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatternsIndexRoute = ApiPatternsIndexRouteImport.update({
  id: '/api/patterns/',
  path: '/api/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatternsIdRoute = ApiPatternsIdRouteImport.update({
  id: '/api/patterns/$id',
  path: '/api/patterns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/api/hatches': typeof ApiHatchesRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/patterns/$id': typeof ApiPatternsIdRoute
  '/api/patterns': typeof ApiPatternsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/api/hatches': typeof ApiHatchesRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/patterns/$id': typeof ApiPatternsIdRoute
  '/api/patterns': typeof ApiPatternsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/api/hatches': typeof ApiHatchesRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/patterns/$id': typeof ApiPatternsIdRoute
  '/api/patterns/': typeof ApiPatternsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/api/hatches'
    | '/login'
    | '/api/auth/$'
    | '/api/patterns/$id'
    | '/api/patterns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/api/hatches'
    | '/login'
    | '/api/auth/$'
    | '/api/patterns/$id'
    | '/api/patterns'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/api/hatches'
    | '/login/'
    | '/api/auth/$'
    | '/api/patterns/$id'
    | '/api/patterns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  ApiHatchesRoute: typeof ApiHatchesRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPatternsIdRoute: typeof ApiPatternsIdRoute
  ApiPatternsIndexRoute: typeof ApiPatternsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hatches': {
      id: '/api/hatches'
      path: '/api/hatches'
      fullPath: '/api/hatches'
      preLoaderRoute: typeof ApiHatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patterns/': {
      id: '/api/patterns/'
      path: '/api/patterns'
      fullPath: '/api/patterns'
      preLoaderRoute: typeof ApiPatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patterns/$id': {
      id: '/api/patterns/$id'
      path: '/api/patterns/$id'
      fullPath: '/api/patterns/$id'
      preLoaderRoute: typeof ApiPatternsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  ApiHatchesRoute: ApiHatchesRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPatternsIdRoute: ApiPatternsIdRoute,
  ApiPatternsIndexRoute: ApiPatternsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
